### ISSUE TITLE
Newly Generated Projects creates XCScheme without a BlueprintIdentifier

### ISSUE THREAD

**Issue by adirburke** [tuist/XcodeProj#509] opened 2019-11-29 12:15 UTC
I am making a build file in swift to replace my Rakefile but as the subject says a newly generated xcodeproj creates schemes files

I made a simply change in 
XCScheme+BuildableReference.swift
```            
           if let blueprintIdentifier = element.attributes["BlueprintIdentifier"]  { 
//                throw XCSchemeError.missing(property: "BlueprintIdentifier")
                blueprint = .string(blueprintIdentifier)
            } else {
                blueprint = .string("")
            }
```

it all works fine. 

The aim was to add `environmentVariables` for the development

**Comment by pepibumur** [comment] 2019-12-03 16:30
Not sure if I get what you are trying to do. Could you expand on your example?

**Comment by pepibumur** [comment] 2020-01-28 14:53
I'm closing this issue since there hasn't been input from the author of the issue.

**Comment by adirburke** [comment] 2020-01-29 00:25
```
#!/usr/bin/swift sh

import Foundation
import XcodeProj  // @tuist ~> 7.5.0
import PathKit

//guard CommandLine.arguments.count == 3 else {
//    let arg0 = Path(CommandLine.arguments[0]).lastComponent
//    fputs("usage: \(arg0) <project> <new-version>\n", stderr)
//    exit(1)
//}
func makeEnvVar() throws {
    let new = XCScheme.EnvironmentVariable.init(variable: "ENV_VAR", value: "SETTINGS", enabled: true)
    let projectPath = Path("Project.xcodeproj")
    let xcodeproj = try XcodeProj(path: projectPath)
    for scheme in xcodeproj.sharedData?.schemes ?? [] {
        if scheme.name == "Target" {
            if scheme.launchAction?.environmentVariables == nil {
                scheme.launchAction?.environmentVariables = [new]
            } else {
                scheme.launchAction?.environmentVariables?.append(new)
            }
        }
    }
    try xcodeproj.write(path: projectPath)
}

func shell() throws -> String {
    let task = Process()
    task.launchPath = "/bin/bash"
    task.arguments = ["-c", "swift package generate-xcodeproj" ]
    task.currentDirectoryPath = "./"

    let pipe = Pipe()
    task.standardOutput = pipe
    try task.run()
    task.waitUntilExit()

    let data = pipe.fileHandleForReading.readDataToEndOfFile()
    guard let output = String(data: data, encoding: .utf8) else {
       return "Error"
    }

    print(output)
    return output
}




print(try shell())

try makeEnvVar()
```

Trying to make a small script to re-generate my xcodeproj and then assign my enviroment vars
Its not able to do that as a newly generated (unopened) xcodeproj doesnt have a ```BlueprintIdentifier``` yet

**Comment by pepibumur** [comment] 2020-01-29 08:41
Thanks for including the example @adirburke. I'll use that to reproduce and fix the issue.

**Comment by daltonclaybrook** [comment] 2021-05-09 22:09
I am running into this issue as well. When generating an Xcode project from a Swift package via `swift package generate-xcodeproj`, it appears that schemes do not contain a `BlueprintIdentifier` in their buildable references. Initialization of the `XcodeProj` succeeds, but the result is an empty array for `XcodeProj.sharedData.schemes`. Naively, it seems like the fix is to make Blueprint optional or to add a new case to `XCScheme.BuildableReference.Blueprint`, e.g.
```swift
private enum Blueprint: Equatable {
    case reference(PBXObjectReference)
    case string(String)
    case none
}
```

**Closed** 2021-06-17 10:02 UTC
