### ISSUE TITLE
Xcode's git source control features don't work

### ISSUE THREAD

**Issue by gubikmic** [tuist/XcodeProj#419] opened 2019-05-04 02:00 UTC
Xcode's integrated git source control features don't work with XcodeProj.

## Steps to reproduce
1. Clone XcodeProj (steps 1-3 from README.md)
    1. Git clone the repository `git@github.com:tuist/xcodeproj.git`.
    2. Generate xcodeproj with `swift package generate-xcodeproj`.
    3. Open `XcodeProj.xcodeproj`.
2. In Xcode: View → Version Editor → Show Version Editor

**Result:**
> **Could not load authors for file 'Sources/XcodeProj/Project/XcodeProj.swift'**
> Error: fatal: no such path 'Sources/XcodeProj/Project/XcodeProj.swift' in HEAD

Alternatively:
1. Step 1. i-iii from above
2. In Xcode: make a small change to some file
3. Source Control → Commit...
4. Enter Commit Message and hit Cmd-Return

**Result:**
> **The working copy “XcodeProj” failed to commit files.**
> error: pathspec 'Sources/XcodeProj/Project/XcodeProj.swift' did not match any file(s) known to git

**Comment by pepibumur** [comment] 2019-05-24 15:37
Hey @gubikmic, is XcodeProj the only Swift Package project with which you are experiencing this?

**Comment by pepibumur** [comment] 2019-06-23 07:58
@gubikmic I'm not able to reproduce this. I was able to follow your steps with no error. Which version of Xcode & git are you using?

**Comment by gubikmic** [comment] 2019-06-24 16:47
Hey, sorry for the late reply!
It still happens with Xcode Version 11.0 beta (11M336w) and git version 2.21.0 (Apple Git-120)

History and source control features do work with `XcodeProj-Carthage.xcodeproj/` though...
It's weird, but since you can't reproduce it, feel free to close it if you want to clean up the open issues.

**Comment by saormart** [comment] 2019-09-26 19:37
I also notice that the git even for local source control is not working properly with xcode 11!
I mean, I have a project with 3rd party library using pod, and after I run pod update, and try to commit the changes with the source control, it just looks like committed, but if you try to commit again, all your files from the pod still in there! I notice that I need to do a mall change manually on each file, save to be able to commit... but if you have more than 500 files to do it manually is a nightmare!

**Comment by khoi** [comment] 2020-04-16 13:05
I briefly looked in to this, and can't reproduce the issue. Xcode `Version 11.4.1 (11E503a)`

**Comment by pepibumur** [comment] 2020-04-27 10:28
I'll close it then. Feel free to open the issue if it still happens.

**Closed by pepibumur** 2020-04-27 10:28 UTC
Labels: type:bug

**Comment by wangzhijw** [comment] 2020-08-06 08:34
my Xcode 11.3.1 has the same issue.
