### ISSUE TITLE
Build Script causes CFPropertyListCreateFromXMLData Error

### ISSUE THREAD

**Issue by Dschee** [tuist/xcodeproj#280] opened 2018-08-08 13:57 UTC
Hi, I currently try to integrate this project in a Command Line Tool that I will open source next week. I'm struggling with a test though where I try to read a Swift Package Manager generated .xcodeproj file (I just ran `swift package init && swift generate-xcodeproj`) where I added the following build script to the main target:

```
if which swiftlint > /dev/null; then
    swiftlint
else
    echo "warning: SwiftLint not installed, download it from https://github.com/realm/SwiftLint"
fi
```

This is a very common type of script amongst the projects I've seen so far (both private & open source) and after adding this build script and trying to read the file using xcodeproj, I get the following error:
```
2018-08-08 15:45:09.885 xctest[25967:224825] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 226. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
Error: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not a valid property list.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Unexpected character / at line 1" UserInfo={NSDebugDescription=Unexpected character / at line 1, kCFPropertyListOldStyleParsingError=Error Domain=NSCocoaErrorDomain Code=3840 "Missing ';' on line 226" UserInfo={NSDebugDescription=Missing ';' on line 226}})))
2018-08-08 15:45:09.886 xctest[25967:224825] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 226. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
```

Before I added the build script (and when I remove it) it works again without any issue. And the pointer to line 226 is actually where the build script is in the pbxproj file. Here's the code which is causing the error:

```
do {
    try XcodeProj(pathString: absolutePathUrl.path)
} catch {
    print("Error: \(error)")
}
```

I tried both the 5.0.0-rc1 and the latest master branch, same issue with both.

<img width="1558" alt="bildschirmfoto 2018-08-08 um 15 48 43" src="https://user-images.githubusercontent.com/6942160/43841671-fb0b5a96-9b23-11e8-9055-e4216bba3949.png">

**Comment by pepibumur** [comment] 2018-08-08 14:26
Thanks @Dschee for reporting this. There must be a bug in the logic that parses the project. I"ll have a look and work on a fix for it.

**Comment by pepibumur** [comment] 2018-08-17 15:58
Hi @Dschee. I tried the same steps that you included and I'm not able to reproduce it. The error that you are getting is thrown by the `PropertyListDecoder` class from `Foundation`. If you look at the error, it complains about the line `226` missing a `;`. Would you mind making it fail again and copying and pasting that fails here? You should get the line from the `project.pbxproj` file.

**Comment by pepibumur** [comment] 2018-08-26 18:41
Any updates here @Dschee?

**Comment by pepibumur** [comment] 2018-09-01 15:01
I'm closing this because I was not able to reproduce it and there wasn't any input from the reporter either. If it keeps happening to you, feel free to re-open the issue @Dschee

**Closed** 2018-09-01 15:01 UTC
Labels: type:bug

**Comment by Dschee** [comment] 2018-09-06 11:41
Hi @pepibumur, sorry for answering a little late, I was on vacation overseas til yesterday. Well you closed the issue a little quick, but that's not a problem, as far as I remember I found aworkaround. The project I came across this issue was open sourced in the meantime: [ProjLint](https://github.com/JamitLabs/ProjLint). Don't know, if this helps you though.

When I come across the issue again, then I'll update you here. For now, keeping this closed is fine for me.

**Comment by pepibumur** [comment] 2018-09-06 13:10
No worries! I hope you enjoyed your vacations. 

I'm sorry if it was a little quick for you, but I had to make a call based on the status of the issue, which had received no answer in about a week. That does not mean it's permanently closed, and it can be reopened at any time if it's something still happening.

Congrats on the project ProjLint project. I'm glad to see xcodeproj's API being used to enforce best practices in Xcode projects.

Since you are now user of xcodeproj, don't hesitate to open issues with feedback to improve the project 😛
